dist: xenial
notifications: {email: false}
matrix:
  include:
    - language: elixir
      elixir: 1.8
      otp_release: 21.2
      env:
        - DISCORD_ADMIN_ID=id
        - DISCORD_CHANNEL=123
        - DISCORD_TOKEN=token
        - DISCORD_USER=123
        - OSUSEARCH_API_KEY=key
        - OSU_API_KEY=key
        - REDDIT_CLIENT_ID=id
        - REDDIT_CLIENT_SECRET=secret
        - REDDIT_PASSWORD=pass
        - REDDIT_SUBREDDIT=sub
        - REDDIT_USERNAME=user
        - REDDIT_USER_AGENT=agent
      before_install: cd server
      script: mix test --no-start
    - language: go
      go: 1.12
      before_install: cd client
