dist: xenial
matrix:
  include:
    - language: elixir
      elixir: 1.7
      otp_release: 21.2
      before_install: cd server
      script:
        - mix test --no-start --cover
        - mix format --check-formatted
    - language: go
      go: 1.11
      addons:
        apt:
          packages: [gcc, libc6-dev, libx11-dev, xorg-dev, libxtst-dev, libpng++-dev, xcb, libxcb-xkb-dev, x11-xkb-utils, libx11-xcb-dev, libxkbcommon-x11-dev,libxkbcommon-dev, xsel, xclip]
      before_install: cd client
      script: go test -v -cover
notifications: {email: false}
