dist: xenial
notifications: {email: false}
matrix:
  include:
    - language: elixir
      elixir: 1.7
      otp_release: 21.2
      before_install: cd server
      script: mix test --no-start
    - language: go
      go: 1.11
      before_install: cd client
