version: 2
jobs:
  server:
    # TODO: This will fail until a 1.9 image is available.
    docker:
      - image: circleci/elixir:1.8
    steps:
      - checkout
      - run: |
          cd server
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix test --no-start
          env MIX_ENV=prod mix release prod
  client:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: |
          cd client
          go test -v
workflows:
  version: 2
  build_and_test:
    jobs:
      - server
      - client
