version: 2
jobs:
  server:
    docker: [image: circleci/elixir:1.8]
    steps:
      - checkout
      - run: |
          cd server
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix test --no-start
  client:
    docker: [image: circleci/golang:1.12]
    steps:
      - checkout
      - run: |
          cd client
          go test -v
workflows:
  version: 2
  build_and_test:
    jobs:
      - server
      - client
